api_url = "http://127.0.0.1:8000"
smtp_server = "localhost"
smtp_port = 25
slack_webhook = ""

db_user = "..."
db_pass = "..."
duckdb_path = ":memory:"

OPENAI_API_KEY = "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"
